apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: hstha/microservice/blog/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manaual:
          - src: "src/**/*.js"
            dest: .
    - image: hstha/microservice/blog/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manaual:
          - src: "*.js"
            dest: .
    - image: hstha/microservice/blog/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manaual:
          - src: "*.js"
            dest: .
    - image: hstha/microservice/blog/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manaual:
          - src: "*.js"
            dest: .
    - image: hstha/microservice/blog/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manaual:
          - src: "*.js"
            dest: .
    - image: hstha/microservice/blog/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manaual:
          - src: "*.js"
            dest: .
